/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StructuredRouteImport } from './routes/structured'
import { Route as RoiRouteImport } from './routes/roi'
import { Route as OtaRouteImport } from './routes/ota'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as CampaignRouteImport } from './routes/campaign'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OtaIndexRouteImport } from './routes/ota.index'
import { Route as OtaAnalyticsRouteImport } from './routes/ota.analytics'
import { Route as OtaStageStageIdRouteImport } from './routes/ota.stage.$stageId'

const StructuredRoute = StructuredRouteImport.update({
  id: '/structured',
  path: '/structured',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiRoute = RoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaRoute = OtaRouteImport.update({
  id: '/ota',
  path: '/ota',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignRoute = CampaignRouteImport.update({
  id: '/campaign',
  path: '/campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OtaIndexRoute = OtaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OtaRoute,
} as any)
const OtaAnalyticsRoute = OtaAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OtaRoute,
} as any)
const OtaStageStageIdRoute = OtaStageStageIdRouteImport.update({
  id: '/stage/$stageId',
  path: '/stage/$stageId',
  getParentRoute: () => OtaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/ota': typeof OtaRouteWithChildren
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
  '/ota/analytics': typeof OtaAnalyticsRoute
  '/ota/': typeof OtaIndexRoute
  '/ota/stage/$stageId': typeof OtaStageStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
  '/ota/analytics': typeof OtaAnalyticsRoute
  '/ota': typeof OtaIndexRoute
  '/ota/stage/$stageId': typeof OtaStageStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaign': typeof CampaignRoute
  '/canvas': typeof CanvasRoute
  '/ota': typeof OtaRouteWithChildren
  '/roi': typeof RoiRoute
  '/structured': typeof StructuredRoute
  '/ota/analytics': typeof OtaAnalyticsRoute
  '/ota/': typeof OtaIndexRoute
  '/ota/stage/$stageId': typeof OtaStageStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaign'
    | '/canvas'
    | '/ota'
    | '/roi'
    | '/structured'
    | '/ota/analytics'
    | '/ota/'
    | '/ota/stage/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/campaign'
    | '/canvas'
    | '/roi'
    | '/structured'
    | '/ota/analytics'
    | '/ota'
    | '/ota/stage/$stageId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaign'
    | '/canvas'
    | '/ota'
    | '/roi'
    | '/structured'
    | '/ota/analytics'
    | '/ota/'
    | '/ota/stage/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignRoute: typeof CampaignRoute
  CanvasRoute: typeof CanvasRoute
  OtaRoute: typeof OtaRouteWithChildren
  RoiRoute: typeof RoiRoute
  StructuredRoute: typeof StructuredRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/structured': {
      id: '/structured'
      path: '/structured'
      fullPath: '/structured'
      preLoaderRoute: typeof StructuredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi': {
      id: '/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof RoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota': {
      id: '/ota'
      path: '/ota'
      fullPath: '/ota'
      preLoaderRoute: typeof OtaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaign': {
      id: '/campaign'
      path: '/campaign'
      fullPath: '/campaign'
      preLoaderRoute: typeof CampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ota/': {
      id: '/ota/'
      path: '/'
      fullPath: '/ota/'
      preLoaderRoute: typeof OtaIndexRouteImport
      parentRoute: typeof OtaRoute
    }
    '/ota/analytics': {
      id: '/ota/analytics'
      path: '/analytics'
      fullPath: '/ota/analytics'
      preLoaderRoute: typeof OtaAnalyticsRouteImport
      parentRoute: typeof OtaRoute
    }
    '/ota/stage/$stageId': {
      id: '/ota/stage/$stageId'
      path: '/stage/$stageId'
      fullPath: '/ota/stage/$stageId'
      preLoaderRoute: typeof OtaStageStageIdRouteImport
      parentRoute: typeof OtaRoute
    }
  }
}

interface OtaRouteChildren {
  OtaAnalyticsRoute: typeof OtaAnalyticsRoute
  OtaIndexRoute: typeof OtaIndexRoute
  OtaStageStageIdRoute: typeof OtaStageStageIdRoute
}

const OtaRouteChildren: OtaRouteChildren = {
  OtaAnalyticsRoute: OtaAnalyticsRoute,
  OtaIndexRoute: OtaIndexRoute,
  OtaStageStageIdRoute: OtaStageStageIdRoute,
}

const OtaRouteWithChildren = OtaRoute._addFileChildren(OtaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignRoute: CampaignRoute,
  CanvasRoute: CanvasRoute,
  OtaRoute: OtaRouteWithChildren,
  RoiRoute: RoiRoute,
  StructuredRoute: StructuredRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
